# Generated by Django 5.2 on 2025-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description_product_image_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
