# Generated by Django 5.2 on 2025-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews')),
            ],
        ),
    ]
