# Generated by Django 5.2 on 2025-04-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.theme'),
        ),
    ]
