# Generated by Django 3.2.16 on 2025-05-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.storecustomeruser'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store', 'session_key'], name='storefront__store_i_69593b_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store', 'user'], name='storefront__store_i_75c35d_idx'),
        ),
    ]
