# Generated by Django 3.2.16 on 2025-05-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storefront', '0002_auto_20250510_2002'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='storefront__store_i_75c35d_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cart',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['content_type', 'object_id'], name='storefront__content_3371fd_idx'),
        ),
    ]
