# Generated by Django 3.2.16 on 2025-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_auto_20250510_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecustomeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
